# Generated by Django 4.1.7 on 2023-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transit_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(default='admin@utoronto.ca', max_length=254)),
                ('capacity', models.PositiveIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
