# Generated by Django 4.1.7 on 2023-02-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_branch_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institution_number',
            new_name='inst_num',
        ),
    ]
