# Generated by Django 4.1.7 on 2023-02-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_rename_institution_number_bank_inst_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='transit_number',
            new_name='transit_num',
        ),
    ]
