# Generated by Django 4.1.7 on 2023-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_rename_transit_number_branch_transit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
